export const FETCH_STATUSS_REQUESTED = 'FETCH_STATUSS_REQUESTED';
export const FETCH_STATUSS_SUCCEEDED = 'FETCH_STATUSS_SUCCEEDED';
export const SORT_STATUSS_REQUESTED = 'SORT_STATUSS_REQUESTED';
export const SORT_STATUSS_SUCCEEDED = 'SORT_STATUSS_SUCCEEDED';
