export const CREATE_SERVER_REQUESTED = 'CREATE_SERVER_REQUESTED';
export const CREATE_SERVER_SUCCEEDED = 'CREATE_SERVER_SUCCEEDED';
export const RENDER_CREATE_SERVER_FORM_REQUESTED = 'RENDER_CREATE_SERVER_FORM_REQUESTED';
