export const SEND_COMMAND_REQUESTED = 'SEND_COMMAND_REQUESTED';
export const SEND_COMMAND_SUCCESSED = 'SEND_COMMAND_SUCCESSED';
export const RENDER_CREATE_COMMAND_FORM_REQUESTED = 'RENDER_CREATE_COMMAND_FORM_REQUESTED';
