export const GET_PROVIDER_REQUESTED = 'GET_PROVIDER_REQUESTED';
export const GET_PROVIDER_SUCCEEDED = 'GET_PROVIDER_SUCCEEDED';
export const EDIT_PROVIDER_REQUESTED = 'EDIT_PROVIDER_REQUESTED';
export const EDIT_PROVIDER_SUCCEEDED = 'EDIT_PROVIDER_SUCCEEDED';
export const DELETE_PROVIDER_REQUESTED = 'DELETE_PROVIDER_REQUESTED';
export const DELETE_PROVIDER_SUCCEEDED = 'DELETE_PROVIDER_SUCCEEDED';
