export const RENDER_PROFILE_DETAIL_FORM = 'RENDER_PROFILE_DETAIL_FORM';
export const FETCH_PROFILE_DETAIL_REQUESTED = 'FETCH_PROFILE_DETAIL_REQUESTED';
export const FETCH_PROFILE_DETAIL_SUCCESSED = 'FETCH_PROFILE_DETAIL_SUCCESSED';
export const FILL_PROFILE_DETAIL_FORM = 'FILL_PROFILE_DETAIL_FORM';
