export const RENDER_EDIT_STATUS_FORM_REQUESTED = 'RENDER_EDIT_STATUS_FORM_REQUESTED';
export const FILL_STATUS_DETAIL_FORM = 'FILL_STATUS_DETAIL_FORM';
export const GET_STATUS_REQUESTED = 'GET_STATUS_REQUESTED';
export const GET_STATUS_SUCCEEDED = 'GET_STATUS_SUCCEEDED';
export const EDIT_STATUS_REQUESTED = 'EDIT_STATUS_REQUESTED';
export const EDIT_STATUS_SUCCEEDED = 'EDIT_STATUS_SUCCEEDED';
export const DELETE_STATUS_REQUESTED = 'DELETE_STATUS_REQUESTED';
export const DELETE_STATUS_SUCCEEDED = 'DELETE_STATUS_SUCCEEDED';
