export const FETCH_SERVERS_REQUESTED = 'FETCH_SERVERS_REQUESTED';
export const FETCH_SERVERS_SUCCEEDED = 'FETCH_SERVERS_SUCCEEDED';
export const SORT_SERVERS_REQUESTED = 'SORT_SERVERS_REQUESTED';
export const SORT_SERVERS_SUCCEEDED = 'SORT_SERVERS_SUCCEEDED';
