export const RENDER_EDIT_SERVER_FORM_REQUESTED = 'RENDER_EDIT_SERVER_FORM_REQUESTED';
export const FILL_SERVER_DETAIL_FORM = 'FILL_SERVER_DETAIL_FORM';
export const GET_SERVER_REQUESTED = 'GET_SERVER_REQUESTED';
export const GET_SERVER_SUCCEEDED = 'GET_SERVER_SUCCEEDED';
export const EDIT_SERVER_REQUESTED = 'EDIT_SERVER_REQUESTED';
export const EDIT_SERVER_SUCCEEDED = 'EDIT_SERVER_SUCCEEDED';
export const DELETE_SERVER_REQUESTED = 'DELETE_SERVER_REQUESTED';
export const DELETE_SERVER_SUCCEEDED = 'DELETE_SERVER_SUCCEEDED';
