export const CREATE_TEST_REQUESTED = 'CREATE_TEST_REQUESTED';
export const CREATE_TEST_SUCCEEDED = 'CREATE_TEST_SUCCEEDED';
export const RENDER_CREATE_TEST_FORM_REQUESTED = 'RENDER_CREATE_TEST_FORM_REQUESTED';

