export const RENDER_EDIT_TEST_FORM_REQUESTED = 'RENDER_EDIT_TEST_FORM_REQUESTED';
export const FILL_TEST_DETAIL_FORM = 'FILL_TEST_DETAIL_FORM';
export const GET_TEST_REQUESTED = 'GET_TEST_REQUESTED';
export const GET_TEST_SUCCEEDED = 'GET_TEST_SUCCEEDED';
export const EDIT_TEST_REQUESTED = 'EDIT_TEST_REQUESTED';
export const EDIT_TEST_SUCCEEDED = 'EDIT_TEST_SUCCEEDED';
export const DELETE_TEST_REQUESTED = 'DELETE_TEST_REQUESTED';
export const DELETE_TEST_SUCCEEDED = 'DELETE_TEST_SUCCEEDED';
