export const GET_ALL_USERS_NO_PAGINATION_REQUESTED = 'GET_ALL_USERS_NO_PAGINATION_REQUESTED';
export const GET_ALL_USERS_NO_PAGINATION_SUCCEEDED = 'GET_ALL_USERS_NO_PAGINATION_SUCCEEDED';

export const ASSIGN_PROJECT_TO_USER_REQUESTED = 'ASSIGN_PROJECT_TO_USER_REQUESTED';
export const ASSIGN_PROJECT_TO_USER_SUCCEEDED = 'ASSIGN_PROJECT_TO_USER_SUCCEEDED';

export const UN_ASSIGN_PROJECT_TO_USER_REQUESTED = 'UN_ASSIGN_PROJECT_TO_USER_REQUESTED';
export const UN_ASSIGN_PROJECT_TO_USER_SUCCEEDED = 'UN_ASSIGN_PROJECT_TO_USER_SUCCEEDED';