export const FETCH_CATEGORIES_REQUESTED = 'FETCH_CATEGORIES_REQUESTED';
export const FETCH_CATEGORIES_SUCCEEDED = 'FETCH_CATEGORIES_SUCCEEDED';
export const SORT_CATEGORIES_REQUESTED = 'SORT_CATEGORIES_REQUESTED';
export const SORT_CATEGORIES_SUCCEEDED = 'SORT_CATEGORIES_SUCCEEDED';
