export const FETCH_ORDER_DETAIL_REQUESTED = 'FETCH_ORDER_DETAIL_REQUESTED';
export const FETCH_ORDER_DETAIL_SUCCEEDED = 'FETCH_ORDER_DETAIL_SUCCEEDED';
export const GET_ORDER_USER_PROFILE = 'GET_ORDER_USER_PROFILE';

