export const GET_DESIGNER_REQUESTED = "GET_DESIGNER_REQUESTED";
export const GET_DESIGNER_SUCCEEDED = "GET_DESIGNER_SUCCEEDED";
export const EDIT_DESIGNER_REQUESTED = "EDIT_DESIGNER_REQUESTED";
export const EDIT_DESIGNER_SUCCEEDED = "EDIT_DESIGNER_SUCCEEDED";
export const DELETE_DESIGNER_REQUESTED = "DELETE_DESIGNER_REQUESTED";
export const DELETE_DESIGNER_SUCCEEDED = "DELETE_DESIGNER_SUCCEEDED";
