export const GET_PROJECT_REQUESTED = 'GET_PROJECT_REQUESTED';
export const GET_PROJECT_SUCCEEDED = 'GET_PROJECT_SUCCEEDED';
export const EDIT_PROJECT_REQUESTED = 'EDIT_PROJECT_REQUESTED';
export const EDIT_PROJECT_SUCCEEDED = 'EDIT_PROJECT_SUCCEEDED';
export const DELETE_PROJECT_REQUESTED = 'DELETE_PROJECT_REQUESTED';
export const DELETE_PROJECT_SUCCEEDED = 'DELETE_PROJECT_SUCCEEDED';
