export const GET_INFO_ENV_REQUESTED = 'GET_INFO_ENV_REQUESTED';
export const GET_INFO_ENV_SUCCEEDED = 'GET_INFO_ENV_SUCCEEDED';
export const EDIT_INFO_ENV_REQUESTED = 'EDIT_INFO_ENV_REQUESTED';
export const EDIT_INFO_ENV_SUCCEEDED = 'EDIT_INFO_ENV_SUCCEEDED';
export const ADD_PROPERTIE_ENV_SUCCESSED = 'ADD_PROPERTIE_ENV_SUCCESSED';
export const ADD_PROPERTIE_ENV_REQUESTED = 'ADD_PROPERTIE_ENV_REQUESTED';
