export const FETCH_PROVIDERS_REQUESTED = 'FETCH_PROVIDERS_REQUESTED';
export const FETCH_PROVIDERS_SUCCEEDED = 'FETCH_PROVIDERS_SUCCEEDED';
export const SORT_PROVIDERS_REQUESTED = 'SORT_PROVIDERS_REQUESTED';
export const SORT_PROVIDERS_SUCCEEDED = 'SORT_PROVIDERS_SUCCEEDED';
