export const FETCH_CUSTOMERS_REQUESTED = 'FETCH_CUSTOMERS_REQUESTED';
export const FETCH_CUSTOMERS_SUCCEEDED = 'FETCH_CUSTOMERS_SUCCEEDED';
export const SORT_CUSTOMERS_REQUESTED = 'SORT_CUSTOMERS_REQUESTED';
export const SORT_CUSTOMERS_SUCCEEDED = 'SORT_CUSTOMERS_SUCCEEDED';
