export const RENDER_EDIT_PROJECT_FORM_REQUESTED = 'RENDER_EDIT_PROJECT_FORM_REQUESTED';
export const FILL_PROJECT_DETAIL_FORM = 'FILL_PROJECT_DETAIL_FORM';
export const FETCH_PROJECT_DETAIL_REQUESTED = 'FETCH_PROJECT_DETAIL_REQUESTED';
export const FETCH_PROJECT_DETAIL_SUCCEEDED = 'FETCH_PROJECT_DETAIL_SUCCEEDED';
export const EDIT_PROJECT_REQUESTED = 'EDIT_PROJECT_REQUESTED';
export const EDIT_PROJECT_SUCCEEDED = 'EDIT_PROJECT_SUCCEEDED';
export const DELETE_PROJECT_REQUESTED = 'DELETE_PROJECT_REQUESTED';
export const DELETE_PROJECT_SUCCEEDED = 'DELETE_PROJECT_SUCCEEDED';
export const UPDATE_UPDATE_PROJECT_INPUT_OPTIONS = 'UPDATE_UPDATE_PROJECT_INPUT_OPTIONS';
export const DELETE_BUILD_PROJECT_REQUESTED = 'DELETE_BUILD_PROJECT_REQUESTED';
export const DELETE_BUILD_PROJECT_SUCCEEDED = 'DELETE_BUILD_PROJECT_SUCCEEDED';

export const BUILD_PROJECT_REQUESTED = 'BUILD_PROJECT_REQUESTED';
export const BUILD_PROJECT_SUCCEEDED = 'BUILD_PROJECT_SUCCEEDED';
