export const RENDER_EDIT_FRAMEWORK_FORM_REQUESTED = 'RENDER_EDIT_FRAMEWORK_FORM_REQUESTED';
export const FILL_FRAMEWORK_DETAIL_FORM = 'FILL_FRAMEWORK_DETAIL_FORM';
export const GET_FRAMEWORK_REQUESTED = 'GET_FRAMEWORK_REQUESTED';
export const GET_FRAMEWORK_SUCCEEDED = 'GET_FRAMEWORK_SUCCEEDED';
export const EDIT_FRAMEWORK_REQUESTED = 'EDIT_FRAMEWORK_REQUESTED';
export const EDIT_FRAMEWORK_SUCCEEDED = 'EDIT_FRAMEWORK_SUCCEEDED';
export const DELETE_FRAMEWORK_REQUESTED = 'DELETE_FRAMEWORK_REQUESTED';
export const DELETE_FRAMEWORK_SUCCEEDED = 'DELETE_FRAMEWORK_SUCCEEDED';
