export const FETCH_PROJECTS_REQUESTED = 'FETCH_PROJECTS_REQUESTED';
export const FETCH_PROJECTS_SUCCEEDED = 'FETCH_PROJECTS_SUCCEEDED';
export const SORT_PROJECTS_REQUESTED = 'SORT_PROJECTS_REQUESTED';
export const SORT_PROJECTS_SUCCEEDED = 'SORT_PROJECTS_SUCCEEDED';
