export const FETCH_PROJECTS_REQUESTED = 'FETCH_PROJECTS_REQUESTED';
export const FETCH_PROJECTS_SUCCEEDED = 'FETCH_PROJECTS_SUCCEEDED';
export const BUILD_PROJECT_REQUESTED = 'BUILD_PROJECT_REQUESTED';
export const BUILD_PROJECT_SUCCEEDED = 'BUILD_PROJECT_SUCCEEDED';

