export const FETCH_ALL_USER_REQUESTED = 'FETCH_ALL_USER_REQUESTED';
export const FETCH_ALL_USER_SUCCEEDED = 'FETCH_ALL_USER_SUCCEEDED';
export const DELETE_USER_REQUESTED = 'DELETE_USER_REQUESTED';
export const DELETE_USER_SUCCEEDED = 'DELETE_USER_SUCCEEDED';
