export const CREATE_FRAMEWORK_REQUESTED = 'CREATE_FRAMEWORK_REQUESTED';
export const CREATE_FRAMEWORK_SUCCEEDED = 'CREATE_FRAMEWORK_SUCCEEDED';
export const RENDER_CREATE_FRAMEWORK_FORM_REQUESTED = 'RENDER_CREATE_FRAMEWORK_FORM_REQUESTED';
