export const UPDATE_ORDER_REQUESTED = 'UPDATE_ORDER_REQUESTED';
export const UPDATE_ORDER_SUCCEEDED = 'UPDATE_ORDER_SUCCEEDED';
export const DELETE_ORDER_REQUESTED = 'DELETE_ORDER_REQUESTED';
export const DELETE_ORDER_SUCCEEDED = 'DELETE_ORDER_SUCCEEDED';
