export const FETCH_FRAMEWORKS_REQUESTED = 'FETCH_FRAMEWORKS_REQUESTED';
export const FETCH_FRAMEWORKS_SUCCEEDED = 'FETCH_FRAMEWORKS_SUCCEEDED';
export const SORT_FRAMEWORKS_REQUESTED = 'SORT_FRAMEWORKS_REQUESTED';
export const SORT_FRAMEWORKS_SUCCEEDED = 'SORT_FRAMEWORKS_SUCCEEDED';
