export const CREATE_PROJECT_REQUESTED = 'CREATE_PROJECT_REQUESTED';
export const CREATE_PROJECT_SUCCEEDED = 'CREATE_PROJECT_SUCCEEDED';
export const RENDER_CREATE_PROJECT_FORM_REQUESTED = 'RENDER_CREATE_PROJECT_FORM_REQUESTED';
export const UPDATE_CREATE_PROJECT_INPUT_OPTIONS = 'UPDATE_CREATE_PROJECT_INPUT_OPTIONS';
