export const CREATE_STATUS_REQUESTED = 'CREATE_STATUS_REQUESTED';
export const CREATE_STATUS_SUCCEEDED = 'CREATE_STATUS_SUCCEEDED';
export const RENDER_CREATE_STATUS_FORM_REQUESTED = 'RENDER_CREATE_STATUS_FORM_REQUESTED';
