export const GET_COURIER_REQUESTED = 'GET_COURIER_REQUESTED';
export const GET_COURIER_SUCCEEDED = 'GET_COURIER_SUCCEEDED';
export const EDIT_COURIER_REQUESTED = 'EDIT_COURIER_REQUESTED';
export const EDIT_COURIER_SUCCEEDED = 'EDIT_COURIER_SUCCEEDED';
export const DELETE_COURIER_REQUESTED = 'DELETE_COURIER_REQUESTED';
export const DELETE_COURIER_SUCCEEDED = 'DELETE_COURIER_SUCCEEDED';
