export const FETCH_CURRENCYS_REQUESTED = 'FETCH_CURRENCYS_REQUESTED';
export const FETCH_CURRENCYS_SUCCEEDED = 'FETCH_CURRENCYS_SUCCEEDED';
export const SORT_CURRENCYS_REQUESTED = 'SORT_CURRENCYS_REQUESTED';
export const SORT_CURRENCYS_SUCCEEDED = 'SORT_CURRENCYS_SUCCEEDED';
