#!/bin/bash

git checkout master
git pull vicoders master
git pull origin master
git push origin master
git push vicoders master

git checkout dev_khu2
git pull vicoders dev_khu2
git pull origin dev_khu2
git push origin dev_khu2
git push vicoders dev_khu2

git checkout dev
git pull vicoders dev
git pull origin dev
git push origin dev
git push vicoders dev
