export const EDIT_CATEGORY_REQUESTED = 'EDIT_CATEGORY_REQUESTED';
export const EDIT_CATEGORY_SUCCEEDED = 'EDIT_CATEGORY_SUCCEEDED';
export const GET_CATEGORY_REQUESTED = 'GET_CATEGORY_REQUESTED';
export const GET_CATEGORY_SUCCEEDED = 'GET_CATEGORY_SUCCEEDED';
export const DELETE_CATEGORY_REQUESTED = 'DELETE_CATEGORY_REQUESTED';
export const DELETE_CATEGORY_SUCCEEDED = 'DELETE_CATEGORY_SUCCEEDED';
