export const CREATE_CATEGORY_REQUESTED = 'CREATE_CATEGORY_REQUESTED';
export const CREATE_CATEGORY_SUCCEEDED = 'CREATE_CATEGORY_SUCCEEDED';
export const RENDER_CREATE_CATEGORY_FORM_REQUESTED = 'RENDER_CREATE_CATEGORY_FORM_REQUESTED';

