export const FETCH_TESTS_REQUESTED = 'FETCH_TESTS_REQUESTED';
export const FETCH_TESTS_SUCCEEDED = 'FETCH_TESTS_SUCCEEDED';
export const SORT_TESTS_REQUESTED = 'SORT_TESTS_REQUESTED';
export const SORT_TESTS_SUCCEEDED = 'SORT_TESTS_SUCCEEDED';
