export const FETCH_PRODUCT_DETAIL_REQUESTED = 'FETCH_PRODUCT_DETAIL_REQUESTED';
export const FETCH_PRODUCT_DETAIL_SUCCEEDED = 'FETCH_PRODUCT_DETAIL_SUCCEEDED';
export const MAP_CATEGORIES_TO_PRODUCT = 'MAP_CATEGORIES_TO_PRODUCT';
