export const FETCH_DESIGNERS_REQUESTED = 'FETCH_DESIGNERS_REQUESTED';
export const FETCH_DESIGNERS_SUCCEEDED = 'FETCH_DESIGNERS_SUCCEEDED';
export const SORT_DESIGNERS_REQUESTED = 'SORT_DESIGNERS_REQUESTED';
export const SORT_DESIGNERS_SUCCEEDED = 'SORT_DESIGNERS_SUCCEEDED';
