export const FETCH_ORDERS_REQUESTED = 'FETCH_ORDERS_REQUESTED';
export const FETCH_ORDER_SUCCEEDED = 'FETCH_ORDER_SUCCEEDED';
export const SORT_ORDERS_REQUESTED = 'SORT_ORDERS_REQUESTED';
export const SORT_ORDERS_SUCCEEDED = 'SORT_ORDERS_SUCCEEDED';
export const UPDATE_ORDER_FILTER = 'UPDATE_ORDER_FILTER';

